"""add_resultados_electorales

Revision ID: befef4721bb7
Revises: 20260322_0003
Create Date: 2026-03-22 15:50:31.672453
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'befef4721bb7'
down_revision = '20260322_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('dep_codigo', sa.String(length=2), nullable=False),
    sa.Column('dep_nombre', sa.String(length=128), nullable=False),
    sa.Column('corporacion_codigo', sa.String(length=4), nullable=False),
    sa.Column('corporacion_nombre', sa.String(length=64), nullable=False),
    sa.Column('votos_total', sa.Integer(), nullable=False),
    sa.Column('votos_validos', sa.Integer(), nullable=False),
    sa.Column('votos_nulos', sa.Integer(), nullable=False),
    sa.Column('votos_blancos', sa.Integer(), nullable=False),
    sa.Column('partido_codigo', sa.String(length=8), nullable=False),
    sa.Column('partido_nombre', sa.String(length=128), nullable=False),
    sa.Column('partido_votos', sa.Integer(), nullable=False),
    sa.Column('top5_candidatos', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'dep_codigo', 'corporacion_codigo', 'partido_codigo', name='uq_resultados_departamento')
    )
    op.create_index('ix_resultados_dep_anio_corp', 'resultados_departamento', ['anio', 'dep_codigo', 'corporacion_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_departamento_anio'), 'resultados_departamento', ['anio'], unique=False)
    op.create_index(op.f('ix_resultados_departamento_corporacion_codigo'), 'resultados_departamento', ['corporacion_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_departamento_dep_codigo'), 'resultados_departamento', ['dep_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_departamento_id'), 'resultados_departamento', ['id'], unique=False)
    op.create_table('resultados_municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mun_codigo', sa.String(length=5), nullable=False),
    sa.Column('mun_nombre', sa.String(length=160), nullable=False),
    sa.Column('dep_codigo', sa.String(length=2), nullable=False),
    sa.Column('corporacion_codigo', sa.String(length=4), nullable=False),
    sa.Column('corporacion_nombre', sa.String(length=64), nullable=False),
    sa.Column('votos_total', sa.Integer(), nullable=False),
    sa.Column('votos_validos', sa.Integer(), nullable=False),
    sa.Column('votos_nulos', sa.Integer(), nullable=False),
    sa.Column('votos_blancos', sa.Integer(), nullable=False),
    sa.Column('partido_codigo', sa.String(length=8), nullable=False),
    sa.Column('partido_nombre', sa.String(length=128), nullable=False),
    sa.Column('partido_votos', sa.Integer(), nullable=False),
    sa.Column('top5_candidatos', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mun_codigo', 'corporacion_codigo', 'partido_codigo', name='uq_resultados_municipio')
    )
    op.create_index('ix_resultados_mun_anio_corp', 'resultados_municipio', ['anio', 'mun_codigo', 'corporacion_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_municipio_anio'), 'resultados_municipio', ['anio'], unique=False)
    op.create_index(op.f('ix_resultados_municipio_corporacion_codigo'), 'resultados_municipio', ['corporacion_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_municipio_dep_codigo'), 'resultados_municipio', ['dep_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_municipio_id'), 'resultados_municipio', ['id'], unique=False)
    op.create_index(op.f('ix_resultados_municipio_mun_codigo'), 'resultados_municipio', ['mun_codigo'], unique=False)
    op.create_table('resultados_pais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('corporacion_codigo', sa.String(length=4), nullable=False),
    sa.Column('corporacion_nombre', sa.String(length=64), nullable=False),
    sa.Column('votos_total', sa.Integer(), nullable=False),
    sa.Column('votos_validos', sa.Integer(), nullable=False),
    sa.Column('votos_nulos', sa.Integer(), nullable=False),
    sa.Column('votos_blancos', sa.Integer(), nullable=False),
    sa.Column('partido_codigo', sa.String(length=8), nullable=False),
    sa.Column('partido_nombre', sa.String(length=128), nullable=False),
    sa.Column('partido_votos', sa.Integer(), nullable=False),
    sa.Column('top5_candidatos', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'corporacion_codigo', 'partido_codigo', name='uq_resultados_pais')
    )
    op.create_index(op.f('ix_resultados_pais_anio'), 'resultados_pais', ['anio'], unique=False)
    op.create_index(op.f('ix_resultados_pais_corporacion_codigo'), 'resultados_pais', ['corporacion_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_pais_id'), 'resultados_pais', ['id'], unique=False)
    op.create_table('resultados_puesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('codigo_puesto', sa.String(length=16), nullable=False),
    sa.Column('mun_codigo', sa.String(length=5), nullable=False),
    sa.Column('dep_codigo', sa.String(length=2), nullable=False),
    sa.Column('corporacion_codigo', sa.String(length=4), nullable=False),
    sa.Column('corporacion_nombre', sa.String(length=64), nullable=False),
    sa.Column('votos_total', sa.Integer(), nullable=False),
    sa.Column('votos_validos', sa.Integer(), nullable=False),
    sa.Column('votos_nulos', sa.Integer(), nullable=False),
    sa.Column('votos_blancos', sa.Integer(), nullable=False),
    sa.Column('partido_codigo', sa.String(length=8), nullable=False),
    sa.Column('partido_nombre', sa.String(length=128), nullable=False),
    sa.Column('partido_votos', sa.Integer(), nullable=False),
    sa.Column('top5_candidatos', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'codigo_puesto', 'corporacion_codigo', 'partido_codigo', name='uq_resultados_puesto')
    )
    op.create_index(op.f('ix_resultados_puesto_anio'), 'resultados_puesto', ['anio'], unique=False)
    op.create_index('ix_resultados_puesto_anio_corp', 'resultados_puesto', ['anio', 'codigo_puesto', 'corporacion_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_puesto_codigo_puesto'), 'resultados_puesto', ['codigo_puesto'], unique=False)
    op.create_index(op.f('ix_resultados_puesto_corporacion_codigo'), 'resultados_puesto', ['corporacion_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_puesto_dep_codigo'), 'resultados_puesto', ['dep_codigo'], unique=False)
    op.create_index(op.f('ix_resultados_puesto_id'), 'resultados_puesto', ['id'], unique=False)
    op.create_index(op.f('ix_resultados_puesto_mun_codigo'), 'resultados_puesto', ['mun_codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_puesto_mun_codigo'), table_name='resultados_puesto')
    op.drop_index(op.f('ix_resultados_puesto_id'), table_name='resultados_puesto')
    op.drop_index(op.f('ix_resultados_puesto_dep_codigo'), table_name='resultados_puesto')
    op.drop_index(op.f('ix_resultados_puesto_corporacion_codigo'), table_name='resultados_puesto')
    op.drop_index(op.f('ix_resultados_puesto_codigo_puesto'), table_name='resultados_puesto')
    op.drop_index('ix_resultados_puesto_anio_corp', table_name='resultados_puesto')
    op.drop_index(op.f('ix_resultados_puesto_anio'), table_name='resultados_puesto')
    op.drop_table('resultados_puesto')
    op.drop_index(op.f('ix_resultados_pais_id'), table_name='resultados_pais')
    op.drop_index(op.f('ix_resultados_pais_corporacion_codigo'), table_name='resultados_pais')
    op.drop_index(op.f('ix_resultados_pais_anio'), table_name='resultados_pais')
    op.drop_table('resultados_pais')
    op.drop_index(op.f('ix_resultados_municipio_mun_codigo'), table_name='resultados_municipio')
    op.drop_index(op.f('ix_resultados_municipio_id'), table_name='resultados_municipio')
    op.drop_index(op.f('ix_resultados_municipio_dep_codigo'), table_name='resultados_municipio')
    op.drop_index(op.f('ix_resultados_municipio_corporacion_codigo'), table_name='resultados_municipio')
    op.drop_index(op.f('ix_resultados_municipio_anio'), table_name='resultados_municipio')
    op.drop_index('ix_resultados_mun_anio_corp', table_name='resultados_municipio')
    op.drop_table('resultados_municipio')
    op.drop_index(op.f('ix_resultados_departamento_id'), table_name='resultados_departamento')
    op.drop_index(op.f('ix_resultados_departamento_dep_codigo'), table_name='resultados_departamento')
    op.drop_index(op.f('ix_resultados_departamento_corporacion_codigo'), table_name='resultados_departamento')
    op.drop_index(op.f('ix_resultados_departamento_anio'), table_name='resultados_departamento')
    op.drop_index('ix_resultados_dep_anio_corp', table_name='resultados_departamento')
    op.drop_table('resultados_departamento')
    # ### end Alembic commands ###
